'use client';
import {useEffect,useMemo,useState} from 'react';
import {request,money,media,optimizedImage,safeMedia} from '../lib/api';
const PAGE=12;
const initial=()=>typeof window==='undefined'?{category:'',search:'',availability:'all'}:(()=>{const q=new URLSearchParams(location.search);return {category:q.get('category')||'',search:q.get('search')||q.get('q')||'',availability:q.get('availability')||'all'}})();
export function ProductCard({product}){const first=media(product),second=product.media?.filter(m=>m.media_type==='image'&&safeMedia(m.url)).find(m=>m.url!==first)?.url;const state=product.status==='sold_out'?'Sold out':product.status==='made_to_order'?'Made to order':'Available';return <a className="product-card" href={`/product/?slug=${encodeURIComponent(product.slug)}`}><div className="product-card__media"><img loading="lazy" src={optimizedImage(first,720)} srcSet={[320,480,720,960].map(w=>`${optimizedImage(first,w)} ${w}w`).join(', ')} sizes="(max-width:600px) 45vw,(max-width:1000px) 30vw,23vw" alt={product.name} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='/assets/media/products/pearl-glow-hero.webp'}}/>{second&&<img className="product-card__second" loading="lazy" src={optimizedImage(second,720)} alt="" onError={e=>e.currentTarget.remove()}/>}</div><div className="product-card__meta"><p className="eyebrow">{product.category_name||'Handmade piece'}</p><span className={`availability-tag ${product.status||'available'}`}>● {state}</span></div><h3>{product.name}</h3><p className="card-price">{money(product)}</p></a>}
export default function Catalogue({featured=false,initialData}){
 const [filters,setFilters]=useState(initial),[input,setInput]=useState(()=>initial().search),[data,setData]=useState(featured&&initialData?initialData:null),[rows,setRows]=useState(featured&&initialData?initialData.products||[]:[]),[error,setError]=useState(''),[busy,setBusy]=useState(!featured),[more,setMore]=useState(false),[retry,setRetry]=useState(0);const [page,setPage]=useState(0);
 useEffect(()=>{if(featured||typeof window==='undefined')return;const back=()=>{const state=initial();setFilters(state);setInput(state.search);setPage(0)};addEventListener('popstate',back);return()=>removeEventListener('popstate',back)},[featured]);
 useEffect(()=>{if(featured)return;const timer=setTimeout(()=>setFilters(f=>f.search===input?f:{...f,search:input}),200);return()=>clearTimeout(timer)},[input,featured]);
 useEffect(()=>{if(featured)return;const q=new URLSearchParams();if(filters.category)q.set('category',filters.category);if(filters.search)q.set('search',filters.search);if(filters.availability!=='all')q.set('availability',filters.availability);if(page)q.set('page',String(page+1));const next=`${location.pathname}${q.size?'?'+q:''}`;if(next!==location.pathname+location.search)history.replaceState(null,'',next);const controller=new AbortController();setBusy(true);setError('');const query=new URLSearchParams({limit:String(PAGE),offset:String(page*PAGE)});if(filters.category)query.set('category',filters.category);if(filters.search)query.set('search',filters.search);request(`/api/products?${query}`,{signal:controller.signal}).then(d=>{if(controller.signal.aborted)return;setData(d);setRows(previous=>page===0?d.products||[]:[...previous,...(d.products||[])])}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[filters,page,retry,featured]);
 useEffect(()=>{if(!featured)return;if(initialData){setData(initialData);setRows((initialData.products||[]).filter(p=>p.is_featured));return}request('/api/products?featured=1&limit=8').then(d=>{setData(d);setRows(d.products||[])}).catch(e=>setError(e.message))},[featured,initialData]);
 const change=(key,value)=>{setPage(0);setRows([]);setFilters(f=>({...f,[key]:value}))};const displayed=useMemo(()=>rows.filter(p=>![false,0,'0'].includes(p.is_active)&&(!featured||p.is_featured)&&((featured||filters.availability==='all')||p.status===filters.availability)),[rows,featured,filters.availability]);const total=featured?displayed.length:Number(data?.total||0);const hasMore=!featured&&rows.length<total;
 return <>{!featured&&<div className="filters"><label className="filter-search">Search pieces<input value={input} onChange={e=>setInput(e.target.value)} placeholder="Search by name or detail…"/></label><div className="chips" aria-label="Category filters">{[['','All pieces'],...(data?.categories||[]).filter(c=>c.is_active!==false).map(c=>[c.slug,c.name])].map(([id,label])=><button key={id} className={filters.category===id?'active':''} aria-pressed={filters.category===id} onClick={()=>change('category',id)}>{label}</button>)}</div><div className="availability-filters" role="group" aria-label="Availability">{[['all','All'],['available','Available'],['made_to_order','Made to order']].map(([id,label])=><button key={id} aria-pressed={filters.availability===id} onClick={()=>change('availability',id)}>{label}</button>)}</div></div>}
 {!featured&&<p className="result-count" aria-live="polite">{busy&&page===0?'Finding your pieces…':`${displayed.length} of ${total} ${total===1?'piece':'pieces'}`}</p>}
 {busy&&page===0&&!displayed.length?<div className="skeleton-grid" aria-label="Loading collection">{Array.from({length:8},(_,i)=><div key={i} className="skeleton"/>)}</div>:<div className={`product-grid ${featured?'featured-grid':''}`}>{displayed.slice(0,featured?8:undefined).map(p=><ProductCard key={p.id||p.slug} product={p}/>)}</div>}
 {error&&<div className="message" role="alert">We couldn't load the collection. <button onClick={()=>setRetry(n=>n+1)}>Try again</button></div>}{!busy&&!error&&!displayed.length&&<div className="message"><span className="bead-illustration" aria-hidden="true">○—●—○</span><h3>Nothing matches that yet.</h3><button onClick={()=>{setInput('');change('category','');setFilters({category:'',search:'',availability:'all'})}}>Clear filters</button><a href="/contact/?type=custom">Ask us to make it ↗</a></div>}
 {hasMore&&<div className="load-more"><button className="button secondary" disabled={busy} onClick={()=>setPage(n=>n+1)}>{busy?'Loading pieces…':'Load more pieces ↓'}</button><span className="sr-only" aria-live="polite">{more?'More pieces loaded':''}</span></div>}</>;
}
