'use client';
import {useEffect,useMemo,useState} from 'react';
import {allProducts,money,media,optimizedImage} from '../lib/api';
export function ProductCard({product}) {return <a className="product-card" href={`/product/?slug=${encodeURIComponent(product.slug)}`}><div className="product-card__media"><img loading="lazy" src={optimizedImage(media(product),700)} alt={product.name} onError={e=>{e.currentTarget.src='/assets/media/products/pearl-glow-hero.webp'}}/></div><p className="eyebrow">{product.category_name||'Handmade piece'}</p><h3>{product.name}</h3><p>{money(product)}</p><span>Discover the piece ↗</span></a>}
export default function Catalogue({featured=false,initialData}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[category,setCategory]=useState(''),[search,setSearch]=useState(''),[stock,setStock]=useState(false);
  useEffect(()=>{if(initialData){setData(initialData);return}if(featured)return;const controller=new AbortController();const params=new URLSearchParams(location.search);setCategory(params.get('category')||'');setSearch(params.get('search')||'');allProducts(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[featured,initialData]);
  const visible=useMemo(()=>data?.products.filter(p=>![false,0,'0'].includes(p.is_active) && (!featured || p.is_featured) && (!category || p.category_slug===category) && (!stock || p.status==='available') && (!search || `${p.name} ${p.description||''} ${p.product_code||''}`.toLowerCase().includes(search.toLowerCase())))||[],[data,featured,category,search,stock]);
  if(error)return <div className="message" role="alert">Collection unavailable: {error} <button onClick={()=>location.reload()}>Try again</button></div>;
  if(!data)return <div className="skeleton-grid" aria-label="Loading collection">{[1,2,3,4].map(n=><div key={n} className="skeleton"/>)}</div>;
  const shown=featured?visible.slice(0,8):visible;
  return <><div className="filters">{!featured&&<><input aria-label="Search pieces" placeholder="Search pieces" value={search} onChange={e=>setSearch(e.target.value)}/><label><input type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/> In stock only</label></>}<div className="chips">{!featured&&[['','All pieces'],...data.categories.filter(c=>c.is_active!==false).map(c=>[c.slug,c.name])].map(([id,label])=><button className={category===id?'active':''} aria-pressed={category===id} key={id} onClick={()=>setCategory(id)}>{label}</button>)}</div></div><p className="result-count">{shown.length} {shown.length===1?'piece':'pieces'}</p><div className="product-grid">{shown.map(p=><ProductCard key={p.id||p.slug} product={p}/>)}</div>{!shown.length&&<div className="message">No pieces match your search. <a href="/contact/">Ask for a custom piece ↗</a></div>}</>;
}
