'use client';
import {useEffect,useState} from 'react';
import Script from 'next/script';
import {request,whatsApp} from '../lib/api';
const key=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY||'';
export default function Enquiry(){const [step,setStep]=useState(1),[form,setForm]=useState({name:'',phone:'',product_name:'',enquiry_type:'product',message:'',website:''}),[product,setProduct]=useState(null),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[phone,setPhone]=useState('919326840719'),[turnstileReady,setTurnstileReady]=useState(false);
  useEffect(()=>{const q=new URLSearchParams(location.search);const slug=q.get('product')||q.get('slug');if(q.get('type')||q.get('notes'))setForm(f=>({...f,enquiry_type:q.get('type')||f.enquiry_type,message:q.get('notes')||f.message}));if(slug)request(`/api/products/${encodeURIComponent(slug)}`).then(d=>{setProduct(d.product);setForm(f=>({...f,product_name:d.product.name}))}).catch(()=>setError('We could not verify this piece. Please return to the product and try again.'));request('/api/bootstrap').then(d=>setPhone(d.settings?.whatsapp_number||phone)).catch(()=>{});},[]);
  useEffect(()=>{if(step===2&&key&&turnstileReady&&window.turnstile&&!document.querySelector('#turnstile iframe'))window.turnstile.render('#turnstile',{sitekey:key,theme:'light'});},[step,turnstileReady]);
  const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
  async function submit(e){e.preventDefault();setError('');if(step===1){if(form.name.trim().length<2||!(/^(?:\+?91)?[6-9]\d{9}$/.test(form.phone.replace(/[\s()-]/g,'')))){setError('Please enter your name and a valid Indian WhatsApp number.');return}setStep(2);return}if(!form.message.trim()){setError('Please describe the piece or idea you have in mind.');return}if(busy)return;const token=key?window.turnstile?.getResponse():'';if(key&&!token){setError('Please complete the security check.');return}setBusy(true);try{const result=await request('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,product_id:product?.id||null,quantity:1,city:'',turnstile_token:token})});setStatus(`Thank you! Your enquiry has been received. Reference: ${result.reference}`);setForm({name:'',phone:'',product_name:'',enquiry_type:'product',message:'',website:''});setStep(1)}catch(e){setError(e.message);window.turnstile?.reset()}finally{setBusy(false)}}
  return <section className="section contact-layout"><div><p className="eyebrow">GET IN TOUCH</p><h1>Let’s create <em>something yours.</em></h1><p>Tell us about a piece you love or a custom idea. We’ll personally reply with the details.</p><a href={whatsApp(phone,`Hello HUSBA Beads, I would like to enquire${product?` about ${product.name}`:''}.`)} target="_blank" rel="noreferrer">Prefer WhatsApp? Message us ↗</a></div><form className="contact-form" onSubmit={submit}><p className="eyebrow">{step===1?'01 / YOUR DETAILS':'02 / YOUR PIECE'}</p>{step===1?<><label>Your name<input required name="name" value={form.name} onChange={change} minLength="2" autoComplete="name"/></label><label>WhatsApp number<input required name="phone" type="tel" value={form.phone} onChange={change} autoComplete="tel"/></label></>:<><label>What are you enquiring about?<select name="enquiry_type" value={form.enquiry_type} onChange={change}><option value="product">A piece from the collection</option><option value="custom">A custom piece</option><option value="bulk">A bulk order</option></select></label><label>Piece name<input name="product_name" value={form.product_name} onChange={change} readOnly={!!product}/></label><label>Your idea<textarea name="message" value={form.message} onChange={change} maxLength="1200" rows="5"/></label><input name="website" value={form.website} onChange={change} tabIndex="-1" autoComplete="off" className="honeypot" aria-hidden="true"/><div id="turnstile"/></>}{error&&<p role="alert" className="form-error">{error}</p>}{status&&<p role="status" className="form-success">{status}</p>}<div className="form-actions">{step===2&&<button type="button" className="button secondary" onClick={()=>setStep(1)}>Back</button>}<button className="button" disabled={busy} type="submit">{busy?'Sending…':step===1?'Continue ↗':'Send enquiry ↗'}</button></div></form>{key&&<Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" strategy="afterInteractive" onLoad={()=>window.turnstile?.ready(()=>setTurnstileReady(true))} onError={()=>setError('Security check unavailable. Please try WhatsApp.')}/>}</section>}
