'use client';
import {useEffect,useState} from 'react';
import {request,safeMedia,safeLink} from '../lib/api';
import Catalogue from './Catalogue';
const shown=(settings,name)=>!['false','0'].includes(String(settings[`show_${name}_section`]));
export default function HomeSections(){const [s,setS]=useState({}),[categories,setCategories]=useState([]),[videos,setVideos]=useState([]),[featuredData,setFeaturedData]=useState(null),[slide,setSlide]=useState(0);
  useEffect(()=>{request('/api/bootstrap').then(d=>{setS(d.settings||{});setCategories(d.categories||[]);setVideos(d.videos||[]);setFeaturedData({products:d.products||[],categories:d.categories||[]});if(d.settings?.seo_title)document.title=d.settings.seo_title}).catch(()=>{setFeaturedData({products:[],categories:[]})});},[]);
  const banners=[1,2,3,4,5].map(i=>safeMedia(s[`banner_image_${i}`])).filter(Boolean);
  useEffect(()=>{if(banners.length<2)return;const timer=setInterval(()=>setSlide(i=>(i+1)%banners.length),6500);return()=>clearInterval(timer)},[banners.join('|')]);
  const heroImage=banners[slide]||safeMedia(s.hero_image_url)||'/assets/media/products/pearl-glow-hero.webp';
  return <><section className="hero"><div className="hero-image" style={{backgroundImage:`linear-gradient(90deg,rgba(30,20,22,.77),rgba(30,20,22,.08)),url("${heroImage}")`}}/>{s.hero_media_type==='video'&&safeMedia(s.hero_video_url)&&<video className="hero-video" autoPlay muted loop playsInline poster={heroImage} src={safeMedia(s.hero_video_url)}/>}<div className="hero-copy"><p className="eyebrow">{s.hero_eyebrow||'HANDMADE IN MUMBAI · SMALL BATCHES'}</p><h1>{s.hero_title||<>Not just a piece.<br/><em>A little part of you.</em></>}</h1><p>{s.hero_copy||'Thoughtfully crafted jewellery for the everyday moments that become yours.'}</p><a className="button light" href={safeLink(s.hero_cta_url)}>{s.hero_cta_text||'Explore the collection'} ↗</a></div><a className="scroll-prompt" href="#featured">Scroll to discover ↓</a>{banners.length>1&&<div className="hero-dots" aria-label="Choose banner">{banners.map((_,i)=><button key={i} onClick={()=>setSlide(i)} aria-label={`Banner ${i+1}`} aria-pressed={slide===i}/>)}</div>}</section>
    {shown(s,'products')&&<section className="section" id="featured"><div className="section-head"><div><p className="eyebrow">{s.featured_eyebrow||'THE COLLECTION'}</p><h2>{s.featured_title||<>Little things, <em>lovingly made.</em></>}</h2><p>{s.featured_copy||'A preview of our favourite pieces. The complete collection is just a click away.'}</p></div><a href="/collections/">View all pieces ↗</a></div><Catalogue featured initialData={featuredData}/></section>}
    {shown(s,'categories')&&categories.length>0&&<section className="section categories"><p className="eyebrow">{s.categories_eyebrow||'BROWSE YOUR WAY'}</p><h2>{s.categories_title||'Find your kind of piece.'}</h2>{s.categories_copy&&<p>{s.categories_copy}</p>}<div className="category-list">{categories.filter(c=>c.is_active!==false).map(c=>{let images={};try{images=JSON.parse(s.category_images||'{}')}catch{}const img=safeMedia(images[c.slug]);return <a key={c.id} href={`/collections/?category=${encodeURIComponent(c.slug)}`} style={img?{backgroundImage:`linear-gradient(#30192344,#30192377),url("${img}")`,backgroundSize:'cover',color:'#fff'}:{}}>{c.name}<span>↗</span></a>})}</div></section>}
    {shown(s,'videos')&&videos.length>0&&<section className="section"><div className="section-head"><div><p className="eyebrow">{s.video_eyebrow||'THE HUSBA EDIT'}</p><h2>{s.video_title||'See what we’re making.'}</h2><p>{s.video_copy||'The little details behind each handmade piece.'}</p></div><a href="/videos/">Watch more ↗</a></div><div className="film-grid">{videos.slice(0,3).filter(v=>safeMedia(v.video_url)).map(v=><video key={v.id} controls playsInline preload="none" src={safeMedia(v.video_url)} poster={safeMedia(v.poster_url)}/>)}</div></section>}
    <section className="section steps"><p className="eyebrow">PERSONAL BY DESIGN</p><h2>Made with you <em>in mind.</em></h2><div className="step-grid">{[['01','Find your favourite','Explore handmade pieces and discover a detail that speaks to you.'],['02','Make it personal','Tell us your colours, your occasion, or the little touches you love.'],['03','Let’s talk details','We’ll confirm availability, price and the next steps personally.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="story-band"><div className="story-picture"/><div><p className="eyebrow">OUR STORY</p><h2>Beauty in the <em>small details.</em></h2><p>Each piece starts with a feeling — a colour, a memory, a moment. We bring it together by hand in Mumbai, one bead at a time.</p><a className="button" href="/story/">Meet HUSBA ↗</a></div></section>
    {shown(s,'enquiry')&&<section className="cta"><p className="eyebrow">{s.enquiry_eyebrow||'A PIECE OF YOUR OWN'}</p><h2>{s.enquiry_title||'Have an idea in mind?'}</h2><p>{s.enquiry_copy||'Tell us what you’re imagining. We would love to make it with you.'}</p><a className="button light" href="/contact/">Start an enquiry ↗</a></section>}</>;
}
