'use client';
import {useEffect,useState} from 'react';
import {request,safeMedia,safeLink,whatsApp,media,money} from '../lib/api';
import Catalogue from './Catalogue';
import AutoFilm from './AutoFilm';
const shown=(settings,name)=>!['false','0'].includes(String(settings[`show_${name}_section`]));
export default function HomeSections(){const [s,setS]=useState({}),[categories,setCategories]=useState([]),[videos,setVideos]=useState([]),[featuredData,setFeaturedData]=useState(null),[slide,setSlide]=useState(0);
 useEffect(()=>{request('/api/bootstrap').then(d=>{setS(d.settings||{});setCategories(d.categories||[]);setVideos(d.videos||[]);setFeaturedData({products:d.products||[],categories:d.categories||[]});if(d.settings?.seo_title)document.title=d.settings.seo_title}).catch(()=>setFeaturedData({products:[],categories:[]}))},[]);
 const banners=[1,2,3,4,5].map(i=>safeMedia(s[`banner_image_${i}`])).filter(Boolean);useEffect(()=>{if(banners.length<2)return;const t=setInterval(()=>setSlide(i=>(i+1)%banners.length),7000);return()=>clearInterval(t)},[banners.join('|')]);const hero=banners[slide]||safeMedia(s.hero_image_url)||media(featuredData?.products?.[0]);const wa=whatsApp(s.whatsapp_number,'Hello HUSBA Beads, I would like to enquire.');let categoryImages={};try{categoryImages=JSON.parse(s.category_images||'{}')}catch{};
 return <><section className="hero thread-hero"><div className="hero-copy"><p className="eyebrow">{s.hero_eyebrow||'HANDMADE IN MUMBAI'}</p><h1>{s.hero_title||<>Not just a piece.<br/><em>A little part of you.</em></>}</h1><p>{s.hero_copy||'Beaded jewellery strung by hand, in small batches, made to be worn and remembered.'}</p><div className="hero-actions"><a className="button" href={safeLink(s.hero_cta_url)}>{s.hero_cta_text||'Explore the collection'} ↗</a><a className="button secondary" href={wa} target="_blank" rel="noreferrer">Enquire on WhatsApp</a></div></div><div className="hero-art"><div className="hero-arch">{s.hero_media_type==='video'&&safeMedia(s.hero_video_url)?<AutoFilm src={s.hero_video_url} poster={safeMedia(s.hero_video_poster_url)||hero} title={s.hero_image_alt||'HUSBA jewellery in motion'}/>:<img src={hero} alt={s.hero_image_alt||'Handmade HUSBA beaded jewellery'} fetchPriority="high" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='/assets/media/products/pearl-glow-hero.webp'}}/>}</div>{featuredData?.products?.[0]&&<a className="hero-chip" href={`/product/?slug=${encodeURIComponent(featuredData.products[0].slug)}`}>{featuredData.products[0].name}<small>{money(featuredData.products[0])}</small></a>}</div><span className="hero-thread" aria-hidden="true"/></section>
 {categories.length>0&&<div className="category-marquee" aria-label="Our categories"><div>{[...categories,...categories].map((c,i)=><span key={`${c.id}-${i}`}>{c.name}<b>●</b></span>)}</div></div>}
 {shown(s,'products')&&<section className="section" id="featured"><div className="section-head"><div><p className="eyebrow">{s.featured_eyebrow||'THE COLLECTION'}</p><h2>{s.featured_title||<>Pieces we're <em>loving.</em></>}</h2><p>{s.featured_copy||'A few favourites, each finished by hand. Find one that feels like you.'}</p></div><a href="/collections/">View all pieces ↗</a></div><Catalogue featured initialData={featuredData}/></section>}
 {shown(s,'categories')&&categories.length>0&&<section className="section categories"><div className="section-head"><div><p className="eyebrow">{s.categories_eyebrow||'FIND YOUR KIND OF PIECE'}</p><h2>{s.categories_title||<>A little something <em>for you.</em></>}</h2></div></div><div className="category-list">{categories.filter(c=>c.is_active!==false).slice(0,5).map(c=>{const image=safeMedia(categoryImages[c.slug])||media(featuredData?.products?.find(p=>p.category_id===c.id));return <a key={c.id} href={`/collections/?category=${encodeURIComponent(c.slug)}`}><img src={image} alt={`${c.name} collection`} loading="lazy"/><span>{c.name} <b>↗</b></span></a>})}</div></section>}
 <section className="craft-section"><div className="craft-image"><img src={safeMedia(s.story_image_url)||'/assets/media/products/pearl-glow-hero.webp'} alt={s.story_image_alt||'Handmade beaded jewellery details'} loading="lazy"/></div><div><p className="eyebrow">THE HANDMADE WAY</p><h2>Strung by hand.<br/><em>Finished with care.</em></h2><p>{s.story_copy||'Every piece begins with a thought, a colour and the careful work of making it yours.'}</p><ol><li><span>01</span>Choose the beads</li><li><span>02</span>Thread and knot</li><li><span>03</span>Check and pack</li></ol><a href="/story/">Our story ↗</a></div></section>
 {shown(s,'videos')&&videos.length>0&&<section className="section"><div className="section-head"><div><p className="eyebrow">THE HUSBA EDIT</p><h2>The Edit</h2><p>A closer look at how our pieces move.</p></div><a href="/videos/">Explore The Edit ↗</a></div><div className="home-films">{videos.filter(v=>safeMedia(v.video_url)).slice(0,4).map(v=><article key={v.id}><AutoFilm src={v.video_url} poster={v.poster_url} title={v.title||'HUSBA product film'}/><h3>{v.title||'A handmade moment'}</h3>{v.product_slug&&<a href={`/product/?slug=${encodeURIComponent(v.product_slug)}`}>View piece ↗</a>}</article>)}</div></section>}
 <section className="section steps"><p className="eyebrow">A PERSONAL PROCESS</p><h2>Made with you <em>in mind.</em></h2><p>No checkout, no rush. Just a conversation.</p><div className="step-grid">{[['01','Pick a piece','Explore the collection and find the little detail you love.'],['02','Message us on WhatsApp','Tell us about your colours, occasion or a personal touch.'],['03','We make it for you','We confirm the details and make your piece with care.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 {shown(s,'enquiry')&&<section className="cta"><p className="eyebrow">{s.enquiry_eyebrow||'MADE FOR YOU'}</p><h2>{s.enquiry_title||<>Want something made <em>just for you?</em></>}</h2><p>{s.enquiry_copy||'Tell us what you have in mind. We would love to make it with you.'}</p><div><a className="button light" href={wa} target="_blank" rel="noreferrer">Start a WhatsApp chat ↗</a><a className="button secondary" href="/contact/">Send an enquiry ↗</a></div></section>}</>;
}
