'use client';
import {useEffect,useRef,useState} from 'react';
import {request,media,safeMedia,money,whatsApp} from '../lib/api';
import {ProductCard} from './Catalogue';
export default function ProductDetail(){const [data,setData]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(0),[phone,setPhone]=useState('919326840719');const touch=useRef(null);
  useEffect(()=>{const slug=new URLSearchParams(location.search).get('slug');if(!slug){setError('Choose a piece from the collection.');return}let active=true;Promise.all([request(`/api/products/${encodeURIComponent(slug)}`),request('/api/bootstrap').catch(()=>null)]).then(([d,b])=>{if(active){setData(d);setPhone(b?.settings?.whatsapp_number||'919326840719');document.title=`${d.product.name} · HUSBA Beads`;const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=d.product.description||d.product.name}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[]);
  if(error)return <section className="section message"><h1>Piece unavailable.</h1><p>{error}</p><a href="/collections/">Browse the collection ↗</a></section>;
  if(!data)return <section className="section message">Preparing your piece…</section>;
  const {product:p,related=[]}=data;const gallery=(p.media||[]).filter(m=>safeMedia(m.url)).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0));const items=gallery.length?gallery:[{url:media(p),media_type:'image',alt_text:p.name}];const current=items[selected]||items[0];const wa=whatsApp(phone,`Hello HUSBA Beads, I’d like to ask about ${p.name}${p.product_code?` (${p.product_code})`:''}.`);
  return <><section className="section product-layout"><div className="gallery"><div className="gallery-main" onTouchStart={e=>touch.current=e.touches[0]?.clientX} onTouchEnd={e=>{if(touch.current===null)return;const delta=e.changedTouches[0]?.clientX-touch.current;touch.current=null;if(Math.abs(delta)>45)setSelected(i=>(i+(delta<0?1:items.length-1))%items.length)}}>{current.media_type==='video'?<video key={current.url} controls playsInline preload="metadata" poster={safeMedia(current.poster_url)||media(p)} src={safeMedia(current.url)} aria-label={`${p.name} video`}/>:<img key={current.url} src={safeMedia(current.url)} alt={current.alt_text||p.name} onError={e=>{e.currentTarget.src='/assets/media/products/pearl-glow-hero.webp'}}/>}</div><div className="thumbnails">{items.map((item,i)=><button key={item.url+i} onClick={()=>setSelected(i)} aria-pressed={i===selected} aria-label={`Show ${item.media_type==='video'?'video':'image'} ${i+1}`}><img src={item.media_type==='video'?safeMedia(item.poster_url)||media(p):safeMedia(item.url)} alt=""/></button>)}</div></div><div className="product-info"><p className="eyebrow">{p.category_name||'THE COLLECTION'}</p><h1>{p.name}</h1>{p.product_code&&<small>PRODUCT CODE · {p.product_code}</small>}<div className="availability">{p.status==='sold_out'?'Currently unavailable':p.status==='made_to_order'?'Made to order':'Available'}</div><strong className="price">{money(p)}</strong><p>{p.description||'Thoughtfully handmade in Mumbai, just for you.'}</p><div className="actions"><a className="button" href={wa} target="_blank" rel="noreferrer">Ask on WhatsApp ↗</a><a className="button secondary" href={`/contact/?product=${encodeURIComponent(p.slug)}`}>Send an enquiry</a></div><dl>{[['Materials',p.materials],['Colours',p.colors],['Size',p.sizes],['Craft','Handmade in Mumbai']].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><button className="share" onClick={()=>navigator.share?navigator.share({title:p.name,url:location.href}).catch(()=>{}):navigator.clipboard.writeText(location.href)}>Share this piece ↗</button></div></section>{related.length>0&&<section className="section"><h2>You may <em>also love.</em></h2><div className="product-grid">{related.filter(p=>![false,0,'0'].includes(p.is_active)).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</>}
