'use client';
import {useEffect,useState} from 'react';
import {instagram,request,whatsApp,safeMedia} from '../lib/api';
export default function Shell({children}) {
  const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[settings,setSettings]=useState({});
  useEffect(()=>{request('/api/bootstrap').then(data=>setSettings(data.settings||{})).catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{});},[]);
  useEffect(()=>{document.body.style.overflow=menu?'hidden':'';const key=e=>{if(e.key==='Escape'){setMenu(false);setSearch(false)}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow='';document.removeEventListener('keydown',key)}},[menu]);
  const links=[['Collection','/collections/'],['The Edit','/videos/'],['Our story','/story/'],['Enquire','/contact/']];
  return <><a className="skip" href="#main">Skip to content</a>{settings.announcement_1&&<div className="announcement">{[1,2,3].map(i=>settings[`announcement_${i}`]).filter(Boolean).join('  ✦  ')}</div>}
    <header className="nav"><a className="wordmark" href="/">{safeMedia(settings.logo_url)?<img className="wordmark-image" src={safeMedia(settings.logo_url)} alt="HUSBA Beads"/>:<>HUSBA <span>Beads</span></>}</a><nav className="desktop-links" aria-label="Main navigation">{links.map(([label,url])=><a key={url} href={url}>{label}</a>)}</nav><div className="nav-actions"><button aria-label="Search" onClick={()=>setSearch(true)}>⌕</button><button aria-label="Open menu" aria-expanded={menu} onClick={()=>setMenu(true)}>☰</button></div></header>
    <main id="main">{children}</main>
    <footer className="footer"><div><p className="eyebrow">HANDCRAFTED IN MUMBAI</p><h2>Not just a piece.<br/><em>A little part of you.</em></h2>{settings.footer_description&&<p>{settings.footer_description}</p>}</div><div><h3>Explore</h3>{links.map(([l,u])=><a key={u} href={u}>{l}</a>)}</div><div><h3>Connect</h3><a href={settings.instagram_url||instagram} target="_blank" rel="noreferrer">Instagram</a><a href={whatsApp(settings.whatsapp_number,'Hello HUSBA Beads, I would like to enquire.')} target="_blank" rel="noreferrer">WhatsApp</a>{settings.email&&<a href={`mailto:${settings.email}`}>{settings.email}</a>}{[['facebook_url','Facebook'],['youtube_url','YouTube'],['pinterest_url','Pinterest'],['tiktok_url','TikTok']].filter(([key])=>{try{return new URL(settings[key]).protocol==='https:'}catch{return false}}).map(([key,label])=><a key={key} href={settings[key]} target="_blank" rel="noreferrer">{label}</a>)}<a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></div><small>© {new Date().getFullYear()} HUSBA Beads · Made with care.</small></footer>
    <a className="floating" href={whatsApp(settings.whatsapp_number,'Hello HUSBA Beads, I would like to enquire.')} target="_blank" rel="noreferrer" aria-label="Enquire on WhatsApp">✦</a>
    {menu&&<div className="overlay" role="dialog" aria-modal="true" aria-label="Menu"><button className="close" autoFocus onClick={()=>setMenu(false)} aria-label="Close menu">×</button><p className="eyebrow">HUSBA BEADS · MUMBAI</p>{links.map(([l,u],i)=><a style={{animationDelay:`${i*70}ms`}} key={u} href={u} onClick={()=>setMenu(false)}>{l}<span>↗</span></a>)}</div>}
    {search&&<div className="search-overlay" role="dialog" aria-modal="true" aria-label="Search collection"><button onClick={()=>setSearch(false)} aria-label="Close search">×</button><form action="/collections/"><label htmlFor="global-search">What are you looking for?</label><input id="global-search" name="search" autoFocus placeholder="Bracelets, necklaces, charms…"/><button type="submit">Search ↗</button></form></div>}</>;
}
