'use client';
import {useEffect,useRef,useState} from 'react';
import {instagram,request,whatsApp,safeMedia,media,money} from '../lib/api';
const links=[['Home','/'],['Collections','/collections/'],['The Edit','/videos/'],['Our Story','/story/'],['Enquire','/contact/']];
export default function Shell({children}){
 const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[settings,setSettings]=useState({}),[categories,setCategories]=useState([]),[query,setQuery]=useState(''),[matches,setMatches]=useState([]),[dismissed,setDismissed]=useState(true),[scrolled,setScrolled]=useState(false),[offline,setOffline]=useState(false);const menuTrigger=useRef(null),searchTrigger=useRef(null),dialog=useRef(null);
 useEffect(()=>{request('/api/bootstrap').then(d=>{setSettings(d.settings||{});setCategories(d.categories||[])}).catch(()=>{});setDismissed(sessionStorage.getItem('husba-announcement-dismissed')==='1');setOffline(!navigator.onLine);const online=()=>setOffline(!navigator.onLine);const scroll=()=>setScrolled(window.scrollY>8);scroll();addEventListener('scroll',scroll,{passive:true});addEventListener('online',online);addEventListener('offline',online);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{});return()=>{removeEventListener('scroll',scroll);removeEventListener('online',online);removeEventListener('offline',online)}},[]);
 useEffect(()=>{if(!menu&&!search)return;const previous=document.activeElement;document.body.style.overflow='hidden';const key=e=>{if(e.key==='Escape'){setMenu(false);setSearch(false)}if(e.key==='Tab'){const elements=[...dialog.current?.querySelectorAll('a[href],button:not([disabled]),input:not([disabled])')||[]].filter(el=>el.offsetParent!==null);if(!elements.length)return;const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);dialog.current?.querySelector('[data-initial-focus]')?.focus();return()=>{document.body.style.overflow='';document.removeEventListener('keydown',key);(menu?menuTrigger.current:searchTrigger.current)?.focus()||previous?.focus?.()}},[menu,search]);
 useEffect(()=>{if(!search||query.trim().length<2){setMatches([]);return}const controller=new AbortController();const timer=setTimeout(()=>request(`/api/products?search=${encodeURIComponent(query.trim())}&limit=6`,{signal:controller.signal}).then(d=>setMatches(d.products||[])).catch(()=>{}),200);return()=>{clearTimeout(timer);controller.abort()}},[query,search]);
 const wa=whatsApp(settings.whatsapp_number,'Hello HUSBA Beads, I would like to enquire.');const messages=[1,2,3].map(i=>settings[`announcement_${i}`]).filter(Boolean);const active=typeof window==='undefined'?'/':location.pathname;
 return <><a className="skip" href="#main">Skip to content</a>{offline&&<div className="offline-banner" role="status">You're offline. Reconnect to view the latest pieces.</div>}{!dismissed&&messages.length>0&&<div className="announcement"><span>{messages.join(' · ')}</span><button onClick={()=>{sessionStorage.setItem('husba-announcement-dismissed','1');setDismissed(true)}} aria-label="Dismiss announcement">×</button></div>}
 <header className={`nav ${scrolled?'nav-scrolled':''}`}><a className="wordmark" href="/">{safeMedia(settings.logo_url)?<img className="wordmark-image" src={safeMedia(settings.logo_url)} alt="HUSBA Beads"/>:<>HUSBA <span>Beads</span></>}</a><nav className="desktop-links" aria-label="Main navigation">{links.map(([label,url])=><a className={active===url?'active':''} aria-current={active===url?'page':undefined} key={url} href={url}>{label}</a>)}</nav><div className="nav-actions"><button ref={searchTrigger} aria-label="Search pieces" onClick={()=>setSearch(true)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" width="23" height="23" aria-hidden="true"><circle cx="10.7" cy="10.7" r="6.7"/><path d="m16 16 5 5"/></svg></button><a className="nav-whatsapp" href={wa} target="_blank" rel="noreferrer">WhatsApp ↗</a><button ref={menuTrigger} className="menu-trigger" aria-label="Open menu" aria-expanded={menu} onClick={()=>setMenu(true)}>☰</button></div></header>
 <main id="main">{children}</main><footer className="footer"><div className="footer-intro"><p className="eyebrow">HUSBA · HANDMADE IN MUMBAI</p><h2>Not just a piece.<br/><em>A little part of you.</em></h2><p>{settings.footer_description||'A little more meaning in the things you wear.'}</p></div><div><h3>Shop</h3>{categories.filter(c=>c.is_active!==false).slice(0,5).map(c=><a key={c.id} href={`/collections/?category=${encodeURIComponent(c.slug)}`}>{c.name}</a>)}<a href="/collections/">All pieces</a></div><div><h3>Explore</h3>{links.slice(2).map(([l,u])=><a key={u} href={u}>{l}</a>)}</div><div><h3>Connect</h3><a href={wa} target="_blank" rel="noreferrer">WhatsApp</a>{settings.email&&<a href={`mailto:${settings.email}`}>{settings.email}</a>}<a href={settings.instagram_url||instagram} target="_blank" rel="noreferrer">Instagram</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></div><small>Handmade in Mumbai · © {new Date().getFullYear()} HUSBA Beads</small></footer><a className="floating" href={wa} target="_blank" rel="noreferrer" aria-label="Enquire on WhatsApp">✦</a>
 {menu&&<div ref={dialog} className="overlay" role="dialog" aria-modal="true" aria-label="Menu"><div className="overlay-top"><span className="wordmark">HUSBA <em>Beads</em></span><button data-initial-focus onClick={()=>setMenu(false)} aria-label="Close menu">×</button></div><p className="eyebrow">A LITTLE PART OF YOU</p><nav>{links.map(([l,u],i)=><a style={{animationDelay:`${i*40}ms`}} key={u} href={u} onClick={()=>setMenu(false)}>{l}<span>↗</span></a>)}</nav><div className="bead-divider" aria-hidden="true"/><a className="button" href={wa} target="_blank" rel="noreferrer">Enquire on WhatsApp ↗</a><a className="overlay-instagram" href={settings.instagram_url||instagram} target="_blank" rel="noreferrer">Instagram ↗</a><p>Not just a piece. A little part of you.</p></div>}
 {search&&<div ref={dialog} className="search-overlay" role="dialog" aria-modal="true" aria-label="Search collection"><button data-initial-focus onClick={()=>setSearch(false)} aria-label="Close search">×</button><div className="search-panel"><p className="eyebrow">FIND YOUR PIECE</p><form action="/collections/"><label htmlFor="global-search">What are you looking for?</label><input id="global-search" name="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bracelets, necklaces, charms…"/><button type="submit">See all results ↗</button></form>{matches.length>0&&<div className="search-results">{matches.map(p=><a key={p.id} href={`/product/?slug=${encodeURIComponent(p.slug)}`}><img src={media(p)} alt="" loading="lazy"/><span>{p.name}<small>{money(p)}</small></span>↗</a>)}</div>}</div></div>}</>;
}
